
Select * From customer limit 20


--Q1 What is total revenue generated by male vs female customers?

SELECT gender, sum(purchase_amount) as revenue
FROM customer
GROUP BY gender


--Q2 Which customer userd discount but still spent more then avg purchase amount
 
SELECT customer_id, purchase_amount 
FROM customer
WHERE purchase_amount >= (SE) AND discount_applied = 'Yes'


--Q3 Which are the top 5 products with highest average review rating?

SELECT item_purchased, AVG(review_rating) as "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY Average Product Rating desc
LIMIT 5


--Q4 Compare the average  Purchase amount between standard and express shipping

SELECT shipping_type,
ROUND(AVG(purchase_amount), 2) as "Average Purchase Amount"
FROM customer
WHERE shipping_type in ("Standard", "Express")
GROUP BY shipping_type


--Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscriber?

SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

--Q6 Which 5 Producsts have highest percentage of purchases with discount applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' Then 1 Else 0 End)/COUNT(*), 2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5;

--Q7 Segment customer into new, loyal and returning  based on their 
--total number of previous purchases and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
CASE 
   WHEN previous_purchases = 1 THEN 'New'
   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
   ELSE 'Loyal'
   END as customer_segment
FROM customer
)

SELECT customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8 What are the top 3 most purchased product within each category

with item_count as (
	SELECT category, item_purchased,
	COUNT(customer_id) as total_orders,
	ROW_NUMBER() over(partition by category order by count(customer_id) Desc) as item_rank
	from customer
	group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <=3

--Q9 Are customer who are repeated buyers(more than 5 previous purchases) also likely to subscribe? 

Select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status ;


--Q10 What is the revenue contribution for each age group?

Select age_group,
sum(purchase_amount) as revenue_generated
from customer
group by age_group
order by revenue_generated desc;
